[package]
name = "resin"
edition = "2021"
version = "0.0.1"
description = "A reactive, probabilistic logic programming language using Reactive Circuits."
repository = "https://github.com/simon-kohaut/resin"
keywords = [
  "probabilistic logic",
  "reactive circuits",
]

[dependencies]
rclrs = "*"
std_msgs = "*"
plotly = "*"
ndarray = "0.14"
ndarray-stats = "*"
ndarray-linalg = { version = "0.13", features = ["openblas-system"] }
clippy = "*"
itertools = "*"
nom = "*"
regex = "*"
lazy_static = "*"
clingo = { version = "0.7.2", features = ["derive"] }
clap = { version = "4.4.1", features = ["derive"] }
